application:
  subdomain: super-productivity
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://super-productivity:80/
services:
  super-productivity:
    # upstream: johannesjo/super-productivity:v19.0.1
    image: registry.lazycat.cloud/czyt/johannesjo/super-productivity:ea4949eb2291b37c
