lzc-sdk-version: "0.1"
name: Super Productivity
package: cloud.lazycat.app.super-productivity
version: 13.0.10
description: an advanced todo list app with integrated Timeboxing and time tracking capabilities.
homepage: https://github.com/johannesjo/super-productivity
author: johannesjo
application:
  subdomain: super-productivity
  background_task: true
  public_path:
    - /
  routes:
    - /=http://super-productivity:80/
services:
  super-productivity:
    image: registry.lazycat.cloud/czyt/johannesjo/super-productivity:7197114f0b2641c9
